nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

packageExtensions:
  "@typescript-eslint/typescript-estree@*":
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"